# Generated by Django 5.0.2 on 2024-02-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/img')),
                ('title', models.CharField(max_length=255)),
                ('offer', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'PRODUCT',
                'verbose_name_plural': 'PRODUCT',
            },
        ),
    ]
